version: "3.8"
services:
  microphone:
    image: "rhasspy/wyoming-mic-external"
    ports:
      - "10600:10600"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "sysdefault"
      - "--debug"
  playback:
    image: "rhasspy/wyoming-snd-external"
    ports:
      - "10601:10601"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "sysdefault"
      - "--debug"
  satellite:
    image: "rhasspy/wyoming-satellite"
    ports:
      - "10700:10700"
    command:
      - "--name"
      - "my satellite"
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-uri"
      - "tcp://playback:10601"
      - "--debug"
